name: 'replicate-action'
description: 'Replicates bounty internal'
author: 'xcorail'
inputs:
  internal_repo: 
    description: 'The destination repo for the internal issue'
    default: 'github/securitylab-bounties'
  existing_issue:
    description: 'Launching on existing issues: we check duplicates, and we do not comment the original issue'
    default: false
  specific_issue:
    description: 'Specific issue to replicate, in case of manual trigger'
    default: ''
runs:
  using: 'node12'
  main: './replicate.js'