name: 'Bounty issue replication workflow'
on:
  issues:
    types: [opened]
jobs:
  build:
    name: replicate-new
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: npm install
      - run: npm run build
      - uses: ./.github/actions/replicate
        with:
          internal_repo: 'github/securitylab-bounties'
          existing_issue: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INT_REPO_TOKEN: ${{ secrets.INT_REPO_TOKEN }}

